name: Check Books Availability and Notify via Slack

on:
  schedule:
    - cron: "0 6 * * *"  # Runs every day at 6:00am
  workflow_dispatch:

env:
  BOOK_LIST: ${{ secrets.BOOK_LIST }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  WEBSITE_URL: ${{ secrets.WEBSITE_URL }}

jobs:
  check-books:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Chromium via snap
      run: |
        sudo snap install chromium --channel=stable
        chromium --version

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      run: uv sync --locked

    - name: Run Book Search Script
      run: uv run python main.py --book-list "$BOOK_LIST" --slack-webhook-url "$SLACK_WEBHOOK_URL" --website-url "$WEBSITE_URL"
